const bookData = {
  A: {
    Adventure: [
      {
        title: "The Adventures of Tom Sawyer",
        author: "Mark Twain",
        authorWiki: "https://en.wikipedia.org/wiki/Mark_Twain",
      },
    ],
    Art: [
      {
        title: "The Art of War",
        author: "Sun Tzu",
        authorWiki: "https://en.wikipedia.org/wiki/Sun_Tzu",
      },
    ],
    Autobiography: [
      {
        title: "The Autobiography of Malcolm X",
        author: "Malcolm X",
        authorWiki: "https://en.wikipedia.org/wiki/Malcolm_X",
      },
    ],
    Architecture: [],
    Anthropology: [],
    Animals: [],
    Action: [],
    Astronomy: [],
    Agriculture: [],
    "Ancient History": [],
    Archaeology: [],
    Anatomy: [],
    Animation: [],
    Advertising: [],
    Almanac: [],
  },
  B: {
    Biography: [
      {
        title: "The Autobiography of Benjamin Franklin",
        author: "Benjamin Franklin",
        authorWiki: "https://en.wikipedia.org/wiki/Benjamin_Franklin",
      },
    ],
    Business: [
      {
        title: "Business Adventures",
        author: "John Brooks",
        authorWiki: "https://en.wikipedia.org/wiki/John_Brooks_(writer)",
      },
    ],
    Botany: [],
    Baking: [],
    Beauty: [],
    "Bible Studies": [],
    Ballet: [],
    "Behavior Science": [],
    Buddhism: [],
    "Brain Science": [],
    "British History": [],
    Budgeting: [],
    "Board Games": [],
    Blockchain: [],
    Branding: [],
  },
  C: {
    Classics: [
      {
        title: "Crime and Punishment",
        author: "Fyodor Dostoevsky",
        authorWiki: "https://en.wikipedia.org/wiki/Fyodor_Dostoevsky",
      },
    ],
    Comedy: [
      {
        title: "Catch-22",
        author: "Joseph Heller",
        authorWiki: "https://en.wikipedia.org/wiki/Joseph_Heller",
      },
    ],
    Crime: [
      {
        title: "The Count of Monte Cristo",
        author: "Alexandre Dumas",
        authorWiki: "https://en.wikipedia.org/wiki/Alexandre_Dumas",
      },
    ],
    Cooking: [],
    Chemistry: [],
    "Children's Literature": [],
    Cybersecurity: [],
    Culture: [],
    Communication: [],
    Cartoons: [],
    "Civil Rights": [],
    Climate: [],
    "Contemporary Fiction": [],
    Coding: [],
    Christianity: [],
  },
  D: {
    Drama: [
      {
        title: "Death of a Salesman",
        author: "Arthur Miller",
        authorWiki: "https://en.wikipedia.org/wiki/Arthur_Miller",
      },
    ],
    Detective: [
      {
        title: "The Da Vinci Code",
        author: "Dan Brown",
        authorWiki: "https://en.wikipedia.org/wiki/Dan_Brown",
      },
    ],
    Dystopian: [
      {
        title: "1984",
        author: "George Orwell",
        authorWiki: "https://en.wikipedia.org/wiki/George_Orwell",
      },
    ],
    DIY: [],
    Design: [],
    "Development Studies": [],
    Drawing: [],
    "Diet & Nutrition": [],
    "Data Science": [],
    "Digital Marketing": [],
    Documentary: [],
    "Dream Interpretation": [],
    "Dog Training": [],
    Democracy: [],
    "Drug Abuse": [],
  },
  E: {
    Education: [],
    Engineering: [],
    Economics: [],
    "Environmental Science": [],
    Erotica: [],
    Essays: [],
    Ethics: [],
    Encyclopedias: [],
    Entrepreneurship: [],
    "Earth Science": [],
    Evolution: [],
    "Eastern Philosophy": [],
    "E-commerce": [],
    "Emotional Intelligence": [],
    "Exercise Science": [],
  },
  F: {
    Fantasy: [
      {
        title: "The Fellowship of the Ring",
        author: "J.R.R. Tolkien",
        authorWiki: "https://en.wikipedia.org/wiki/J._R._R._Tolkien",
      },
    ],
    Fiction: [
      {
        title: "The Great Gatsby",
        author: "F. Scott Fitzgerald",
        authorWiki: "https://en.wikipedia.org/wiki/F._Scott_Fitzgerald",
      },
    ],
    "Fairy Tales": [
      {
        title: "Grimm's Fairy Tales",
        author: "Brothers Grimm",
        authorWiki: "https://en.wikipedia.org/wiki/Brothers_Grimm",
      },
    ],
    Folklore: [],
    Food: [],
    Fashion: [],
    "Film Studies": [],
    Finance: [],
    Fitness: [],
    Forensics: [],
    "French Literature": [],
    Farming: [],
    Feminism: [],
    "Freedom Fighters": [],
    Futurism: [],
  },
  G: {
    Geography: [],
    Genetics: [],
    Gardening: [],
    "Graphic Novels": [],
    Geology: [],
    "Ghost Stories": [],
    "Global Warming": [],
    Government: [],
    Grammar: [],
    "Game Development": [],
    "Greek Mythology": [],
    "Gender Studies": [],
    "Growth Mindset": [],
    "German Literature": [],
    Golf: [],
  },
  H: {
    History: [
      {
        title: "A History of Western Philosophy",
        author: "Bertrand Russell",
        authorWiki: "https://en.wikipedia.org/wiki/Bertrand_Russell",
      },
    ],
    Horror: [
      {
        title: "The Haunting of Hill House",
        author: "Shirley Jackson",
        authorWiki: "https://en.wikipedia.org/wiki/Shirley_Jackson",
      },
    ],
    "Historical Fiction": [
      {
        title: "The Help",
        author: "Kathryn Stockett",
        authorWiki: "https://en.wikipedia.org/wiki/Kathryn_Stockett",
      },
    ],
    Health: [],
    "Human Rights": [],
    Humor: [],
    Hacking: [],
    Handicrafts: [],
    "Home Improvement": [],
    Hinduism: [],
    Hypnosis: [],
    "Human Anatomy": [],
    Hiking: [],
    "Hero Biographies": [],
    Habits: [],
  },
  I: {
    Inspirational: [],
    Investing: [],
    "Indian Literature": [],
    Innovation: [],
    Islam: [],
    "Interior Design": [],
    Internet: [],
    Intelligence: [],
    "International Relations": [],
    Illustration: [],
    "Industrial Design": [],
    "Information Technology": [],
    "Italian Literature": [],
    Immigration: [],
    Identity: [],
  },
  J: {
    Journalism: [],
    "Japanese Literature": [],
    Justice: [],
    "Juvenile Fiction": [],
    Jazz: [],
    Jokes: [],
    "Jewish Studies": [],
    Journaling: [],
    "Job Search": [],
    "Jungian Psychology": [],
    "Jury Trials": [],
    "Java Programming": [],
    "Japanese History": [],
    "Jewelry Design": [],
    Judo: [],
  },
  K: {
    Knowledge: [],
    Kindness: [],
    Kinetics: [],
    "Kids' Stories": [],
    "Korean Literature": [],
    Karate: [],
    Knitting: [],
    Kingdoms: [],
    Keyboards: [],
    "Kitchen Science": [],
    Kabbalah: [],
    "K-pop": [],
    "King Biographies": [],
    "Kaleidoscope Art": [],
    "K-Drama": [],
  },
  L: {
    Literature: [],
    Law: [],
    "Love Stories": [],
    Languages: [],
    Leadership: [],
    Logic: [],
    Lifestyle: [],
    "LGBTQ+": [],
    Linguistics: [],
    Legends: [],
    "Latin American Studies": [],
    "Life Skills": [],
    "Learning Methods": [],
    "Light Novels": [],
    "Library Science": [],
  },
  M: {
    Mystery: [
      {
        title: "Murder on the Orient Express",
        author: "Agatha Christie",
        authorWiki: "https://en.wikipedia.org/wiki/Agatha_Christie",
      },
    ],
    Mythology: [
      {
        title: "Mythology: Timeless Tales of Gods and Heroes",
        author: "Edith Hamilton",
        authorWiki: "https://en.wikipedia.org/wiki/Edith_Hamilton",
      },
    ],
    Memoir: [
      {
        title: "Man's Search for Meaning",
        author: "Viktor E. Frankl",
        authorWiki: "https://en.wikipedia.org/wiki/Viktor_Frankl",
      },
    ],
    Management: [],
    Medicine: [],
    Military: [],
    Meditation: [],
    Marketing: [],
    "Machine Learning": [],
    "Mental Health": [],
    Music: [],
    Motivation: [],
    Mechanics: [],
    "Modern Art": [],
    Movies: [],
  },
  N: {
    "Non-fiction": [],
    Nature: [],
    Novels: [],
    Neuroscience: [],
    Nutrition: [],
    Navigation: [],
    Nationalism: [],
    Nursing: [],
    "New Age": [],
    "Number Theory": [],
    "Nordic Culture": [],
    Notebooks: [],
    "National Parks": [],
    "Native Studies": [],
    "News Media": [],
  },
  O: {
    Occult: [],
    Oceanography: [],
    Opera: [],
    "Online Business": [],
    "Outdoor Survival": [],
    Origami: [],
    "Object-Oriented Programming": [],
    Oratory: [],
    "Organic Farming": [],
    Optimization: [],
    "Old Testament": [],
    "Outer Space": [],
    Outreach: [],
    "Open Source": [],
    "Occupational Therapy": [],
  },
  P: {
    Poetry: [
      {
        title: "Paradise Lost",
        author: "John Milton",
        authorWiki: "https://en.wikipedia.org/wiki/John_Milton",
      },
    ],
    Philosophy: [
      {
        title: "The Republic",
        author: "Plato",
        authorWiki: "https://en.wikipedia.org/wiki/Plato",
      },
    ],
    Psychology: [
      {
        title: "Thinking, Fast and Slow",
        author: "Daniel Kahneman",
        authorWiki: "https://en.wikipedia.org/wiki/Daniel_Kahneman",
      },
    ],
    Politics: [],
    Physics: [],
    Programming: [],
    "Personal Development": [],
    Parenting: [],
    Photography: [],
    Paranormal: [],
    Painting: [],
    "Public Speaking": [],
    "Project Management": [],
    "Pop Culture": [],
    Pets: [],
  },
  Q: {
    "Quantum Physics": [],
    Quizzes: [],
    "Quirky Fiction": [],
    "Quality Control": [],
    "Quran Studies": [],
    "Quick Recipes": [],
    "Quotation Books": [],
    "Quest Stories": [],
    "Queer Studies": [],
    Quakerism: [],
    "Quiz Books for Kids": [],
    "Quiet Living": [],
    Qigong: [],
    "Quick Reference": [],
    "Queen Biographies": [],
  },
  R: {
    Romance: [],
    Religion: [],
    Robotics: [],
    "Reading Skills": [],
    "Real Estate": [],
    "Russian Literature": [],
    Research: [],
    Relationships: [],
    "Rural Development": [],
    "Renaissance Art": [],
    "Radio Communication": [],
    Rhetoric: [],
    Running: [],
    "Risk Management": [],
    "Refugee Studies": [],
  },
  S: {
    Science: [
      {
        title: "A Brief History of Time",
        author: "Stephen Hawking",
        authorWiki: "https://en.wikipedia.org/wiki/Stephen_Hawking",
      },
    ],
    "Science Fiction": [
      {
        title: "The Stars My Destination",
        author: "Alfred Bester",
        authorWiki: "https://en.wikipedia.org/wiki/Alfred_Bester",
      },
    ],
    "Self-Help": [
      {
        title: "The 7 Habits of Highly Effective People",
        author: "Stephen Covey",
        authorWiki: "https://en.wikipedia.org/wiki/Stephen_Covey",
      },
    ],
    Sports: [],
    "Short Stories": [],
    Sociology: [],
    Spirituality: [],
    Statistics: [],
    Space: [],
    Satire: [],
    Survival: [],
    "Software Engineering": [],
    Storytelling: [],
    "Social Media": [],
    Strategy: [],
  },
  T: {
    Technology: [],
    Travel: [],
    Thriller: [],
    "True Crime": [],
    Teaching: [],
    "Time Management": [],
    Tarot: [],
    "Teen Fiction": [],
    Theology: [],
    Translations: [],
    "Typing Skills": [],
    "Typographic Design": [],
    Teamwork: [],
    "Tai Chi": [],
    Theatre: [],
  },
  U: {
    "Urban Fiction": [],
    "Utopian Literature": [],
    "USA History": [],
    "User Experience": [],
    "Universe Studies": [],
    "Urdu Literature": [],
    "Underwater Exploration": [],
    "UX Design": [],
    "Unsolved Mysteries": [],
    "Unix Systems": [],
    "Urban Planning": [],
    "Unemployment Studies": [],
    "Usability Testing": [],
    "U.S. Presidents": [],
    "Understanding Emotions": [],
  },
  V: {
    Vocabulary: [],
    "Veterinary Science": [],
    "Violence Studies": [],
    "Visual Arts": [],
    Virology: [],
    "Victorian Literature": [],
    "Video Games": [],
    Volunteering: [],
    "Voting Rights": [],
    "Value Education": [],
    Veganism: [],
    "Virtual Reality": [],
    "Vedic Literature": [],
    "Venture Capital": [],
    "Vocal Training": [],
  },
  W: {
    Writing: [],
    War: [],
    "World History": [],
    "Women's Studies": [],
    "Western Fiction": [],
    Wildlife: [],
    "Web Development": [],
    Witchcraft: [],
    Weather: [],
    "World Cultures": [],
    Wellness: [],
    "Wilderness Survival": [],
    "World Religions": [],
    "Water Science": [],
    "Wealth Management": [],
  },
  X: {
    Xenobiology: [],
    "Xbox Games": [],
    "Xenophobia Studies": [],
    "X-ray Science": [],
    "XML Programming": [],
    "X-Games": [],
    "Xhosa Culture": [],
    "Xylophone Music": [],
    "X-Men Comics": [],
    "X-ray Crystallography": [],
    "Xenon Chemistry": [],
    "Xhosa Literature": [],
    "Xtreme Sports": [],
    "X-Rated Literature": [],
    "Xerox Technology": [],
  },
  Y: {
    Yoga: [],
    "Young Adult": [],
    "Yiddish Literature": [],
    "Youth Fiction": [],
    Yearbooks: [],
    "Yoga Philosophy": [],
    "Youth Empowerment": [],
    "YouTube Marketing": [],
    "Youth Sports": [],
    "Yin Yoga": [],
    "Your Life Guide": [],
    "Y2K Culture": [],
    "Youth Counseling": [],
    "Young Innovators": [],
    "Yarn Crafts": [],
  },
  Z: {
    Zoology: [],
    "Zen Buddhism": [],
    Zombies: [],
    Zines: [],
    "Zen Philosophy": [],
    "Zero Waste": [],
    Zodiac: [],
    "Zulu Culture": [],
    "Zoom Culture": [],
    Zumba: [],
    "Zen Stories": [],
    "Zigzag Books": [],
    "Zombie Survival": [],
    Zionism: [],
    "Zesty Cooking": [],
  },
};
